services:

    mongodb:
        image: mongo:8.0.12-rc0-noble
        restart: always
        ports:
            - "27017:27017"
        # command: [--auth]
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongo_data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/
            ME_CONFIG_BASICAUTH: true
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin123
        depends_on:
            - mongodb

    cache:
        image: redis
        container_name: cache
        restart: always
        ports:
          - '6379:6379'
        volumes:
          - cache-data:/data

volumes:
  mongo_data:
  cache-data: